server:
   port: 8080
spring:
  application:
    name: USER-PNR
   
  datasource:
    #url: jdbc:mysql://loan-database.csvdapafimjr.us-east-1.rds.amazonaws.com/loan_live?useServerPrepStmts=false&rewriteBatchedStatements=true
    url: jdbc:mysql://msrlive.cepm4hbwpnht.us-east-1.rds.amazonaws.com/msr_live?useServerPrepStmts=false&rewriteBatchedStatements=true
    username: admin
    password: pixeltechlab###123
         
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl 
    show-sql: true
